package helloservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2021-12-29T04:47:01.945Z
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://helloservice/", name = "HelloServicePortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
@XmlSeeAlso({ObjectFactory.class})
public interface HelloServicePortType {

    @WebMethod(operationName = "HelloWorld", action = "http://helloservice/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://helloservice/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorldResponse")
    public java.lang.String helloWorld();
}
