package helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import jakarta.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2021-12-29T04:47:01.945Z
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://helloservice/", name = "HelloServicePortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface HelloServicePortType {

    @WebMethod(operationName = "SayHello", action = "http://helloservice/SayHello")
    @RequestWrapper(localName = "SayHello", targetNamespace = "http://helloservice/", className = "helloservice.SayHello")
    @ResponseWrapper(localName = "SayHelloResponse", targetNamespace = "http://helloservice/", className = "helloservice.SayHelloResponse")
    @WebResult(name = "SayHelloResult", targetNamespace = "http://helloservice/")
    public java.lang.String sayHello(

        @WebParam(name = "name", targetNamespace = "http://helloservice/")
        java.lang.String name
    );

    @WebMethod(operationName = "HelloWorld", action = "http://helloservice/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://helloservice/")
    public java.lang.String helloWorld();
}
