
package helloservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://helloservice/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface HelloServicePort {

    /**
     * 
     * @return
     *         returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://helloservice/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://helloservice/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorldResponse")
    public String helloWorld();
}
