
package helloservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://helloservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServicePort {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://helloservice/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://helloservice/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://helloservice/", className = "helloservice.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SayHello", action = "http://helloservice/SayHello")
    @WebResult(name = "SayHelloResult", targetNamespace = "http://helloservice/")
    @RequestWrapper(localName = "SayHello", targetNamespace = "http://helloservice/", className = "helloservice.SayHello")
    @ResponseWrapper(localName = "SayHelloResponse", targetNamespace = "http://helloservice/", className = "helloservice.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "http://helloservice/")
        String name);

}
